<a href="https://colab.research.google.com/github/veniapputrii/Data-Analyst-using-Python/blob/main/Python_ETL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#15. Feb
import pandas as pd
#Tabelle 1. Die Mitarbeiter
daten_m = {
    'Name' : ['Anna', 'Ben', 'Clara', 'David'],
    'Team_Code' : [1,2,1,3] #Das ist der Schlüssel
}

df_mitarbeitr = pd.DataFrame(daten_m)

#Tabelle 2 : Die Team-Namen
daten_t = {
    'ID' : [1,2,3],
    'Team_Name' : ['IT', 'Sales', 'HR'] #Die Übersetzung für den Code
}

df_teams = pd.DataFrame(daten_t)

print("___Tabelle 1: Mitarbeiter ___")
display(df_mitarbeitr)
print("___Tabelle 2: Teams ___")
display(df_teams)

___Tabelle 1: Mitarbeiter ___

    Name  Team_Code
0   Anna          1
1    Ben          2
2  Clara          1
3  David          3

___Tabelle 2: Teams ___

   ID Team_Name
0   1        IT
1   2     Sales
2   3        HR

In [ ]:
# 16.Feb
df_komplett = pd.merge(
    df_mitarbeitr,
    df_teams,
    left_on = 'Team_Code',
    right_on= 'ID'
)

display(df_komplett)

    Name  Team_Code  ID Team_Name
0   Anna          1   1        IT
1    Ben          2   2     Sales
2  Clara          1   1        IT
3  David          3   3        HR

In [ ]:
#17. Feb
daten_m = {
    'Name' : ['Anna','Ben','Clara','David', 'Emil'],
    'Team_Code' : [1,2,1,3,99],
    'Stadt' : ['Berlin', 'Hamburg', 'München', 'Berlin', 'Frankfurt'],
    'ID'  : [1,2,3,4,5]
}
df_mitarbeiter_neu = pd.DataFrame(daten_m)
print(df_mitarbeiter_neu)

    Name  Team_Code      Stadt  ID
0   Anna          1     Berlin   1
1    Ben          2    Hamburg   2
2  Clara          1    München   3
3  David          3     Berlin   4
4   Emil         99  Frankfurt   5

In [ ]:
#19. Feb. 2026
#Ich will ganz bestimmte Daten daraus filtern

df_komplett2 = pd.merge(
    df_komplett,
    df_mitarbeiter_neu,
    left_on = 'Team_Code',
    right_on = 'ID'
)

display(df_komplett2)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y    Stadt  ID_y
0   Anna            1     1        IT   Anna            1   Berlin     1
1    Ben            2     2     Sales    Ben            2  Hamburg     2
2  Clara            1     1        IT   Anna            1   Berlin     1
3  David            3     3        HR  Clara            1  München     3

In [ ]:
#20. Feb. 2026
#Ich zeige euch alle Kunden aus Berlin
filter_Stadt = df_komplett2['Stadt'] == 'Berlin'

Berliner = df_komplett2[filter_Stadt]
display(Berliner)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y   Stadt  ID_y
0   Anna            1     1        IT   Anna            1  Berlin     1
2  Clara            1     1        IT   Anna            1  Berlin     1

In [ ]:
#UNd zeige euch alle Mitarbeiter aus Team '1'
filter_Team = df_komplett2['Team_Code_x'] == 1

Ersteteam = df_komplett2[filter_Team]
display(Ersteteam)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y   Stadt  ID_y
0   Anna            1     1        IT   Anna            1  Berlin     1
2  Clara            1     1        IT   Anna            1  Berlin     1

In [ ]:
id = df_komplett2[df_komplett2['ID_x'] == 1]
display(id)

  Name_x  Team_Code_x  ID_x Team_Name Name_y  Team_Code_y   Stadt  ID_y
0   Anna            1     1        IT   Anna            1  Berlin     1
2  Clara            1     1        IT   Anna            1  Berlin     1

In [ ]:
#21. Feb. 2026
#ICh suche : Team_Code ist 1 UND der Name ist 'Anna'

filter_kombination = (df_mitarbeiter_neu['Team_Code'] == 1) & (df_mitarbeiter_neu['Name'] == 'Anna')

ergebnis = df_mitarbeiter_neu[filter_kombination]
print(ergebnis)

   Name  Team_Code   Stadt  ID
0  Anna          1  Berlin   1

In [ ]:
#Spalte entfernen
#axis = 0 -> Zeile löschen
#axis = 1 -> Spalte löschen

df_mitarbeiter_neu = id.drop(['Team_Name', 'Team_Code_y', 'Name_y', 'ID_x'], axis=1)
print(df_mitarbeiter_neu)

  Name_x  Team_Code_x   Stadt  ID_y
0   Anna            1  Berlin     1
2  Clara            1  Berlin     1

In [ ]:
#Neue Spalte 'Abteilung' erstellen und mit 5 Werten füllen
df_mitarbeiter_neu['Abteilung'] = ['IT', 'Sales']
print (df_mitarbeiter_neu)

  Name_x  Team_Code_x   Stadt  ID_y Abteilung
0   Anna            1  Berlin     1        IT
2  Clara            1  Berlin     1     Sales

In [ ]:
#Ersetze die 1 von Clara durch eine 4 in der Spalte 'Team_Code'
df_mitarbeiter_neu['Team_Code_x'] = df_mitarbeiter_neu['Team_Code_x'].replace(1, 2)

print(df_mitarbeiter_neu)

  Name_x  Team_Code_x   Stadt  ID_y Abteilung
0   Anna            2  Berlin     1        IT
2  Clara            2  Berlin     1     Sales

In [ ]:
#Ändere Anna's Team_Code_x von 2 zu 1
df_mitarbeiter_neu.loc[df_mitarbeiter_neu['Name_x'] == 'Anna', 'Team_Code_x'] = 1

print(df_mitarbeiter_neu)

  Name_x  Team_Code_x   Stadt  ID_y Abteilung
0   Anna            1  Berlin     1        IT
2  Clara            2  Berlin     1     Sales

In [ ]:
#22. Feb. 2026
import pandas as pd
#1. Unsere bisherige Tabelle (sauberer Neustart)
daten_m = {
    'Name' : ['Anna', 'Ben', 'Clara', 'David', 'Emil'],
    'Team_Code' : [1,2,1,3,4],
    'Abteilung' : ['IT', 'Sales', 'IT', 'HR', 'Sales']
}
df_mitararbeiter = pd.DataFrame(daten_m)

#2. Ein neues Dictionary mitt den euen Mitarbeitern erstellen

neue_daten = {
    'Name' : ['Fion', 'Gustav', 'Hanna', 'Ida', 'Jan'],
    'Team_Code' : [1,2,1,3,4],
    'Abteilung' : ['IT', 'Sales', 'Marketing', 'IT', 'Sales']
}
df_neu = pd.DataFrame(neue_daten)

#3. Beide Tabellen zusammenfügen
#Die eckigen Klammern [ ] sin wichtig! ignore_index=True sorgt dafür,
#dass die zeilennummern (0,1,2,...) sauber weiterzählen

df_komplett = pd. concat([df_mitararbeiter, df_neu], ignore_index=True)

print(df_komplett)

     Name  Team_Code  Abteilung
0    Anna          1         IT
1     Ben          2      Sales
2   Clara          1         IT
3   David          3         HR
4    Emil          4      Sales
5    Fion          1         IT
6  Gustav          2      Sales
7   Hanna          1  Marketing
8     Ida          3         IT
9     Jan          4      Sales

In [ ]:
#23. Feb. 2026
#Ich filtere wieder nur die Leute aus Team 1 heraus
team_1 = df_komplett[df_komplett['Team_Code'] == 1]

#2. Ich lasse Python zählen, wie oft jede Abteilung in Team 1 vorkommt
verteilung_team_1 = team_1['Abteilung'].value_counts()

print('Verteilung in Team is :')
print(verteilung_team_1)

Verteilung in Team is :
Abteilung
IT           3
Marketing    1
Name: count, dtype: int64